import { Theme } from "daisyui";

export const APP_THEMES: Theme[] = ["black", "nord"];

export const EMAIL_REGEX = /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/;

export enum COOKIE {
  TOKEN = "CUSTOMER_TOKEN",
}

export enum LOCAL_STORAGE {
  IS_SIDEBAR_COLLAPSED = "IS_SIDE_BAR_COLLAPSED",
  USER = "CUSTOMER",
  THEME = "THEME",
}

export enum DIALOG_TYPES {
  BUY_NOW = "BUY_NOW",
  CHECKOUT = "CHECKOUT",
}

export enum CUSTOMER_ORDER_STATUS {
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
}

export enum CUSTOMER_ORDER_VENDOR_STATUS {
  NEW = "NEW",
  CANCELLED = "CANCELLED",
  ACCEPTED = "ACCEPTED",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
}

export enum CUSTOMER_ORDER_VENDOR_PRODUCT_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  CANCELLED = "CANCELLED",
}

export enum DELIVERY_ORDER_STATUS {
  NEW = "NEW",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
}

export enum DELIVERY_STATUS {
  PENDING = "PENDING",
  DELIVERING = "DELIVERING",
  DELIVERED = "DELIVERED",
}
